### ISSUE TITLE
Store & show messages that potato come from

### ISSUE THREAD

**Issue by wmak** [getsentry/gib-potato#13]
HeyTaco had a feature where you could see all tacos you've given and tacos you've recieved, which is great around peer-review time since you could skim heytaco records to know what kind of kudos your peers you've given/received your peers.

AFAIK it was only given/received for the person logged in and nobody else could see it either since i assume it could be problematic with private channels if everyone could see the messages

**Comment by cleptric** [comment]
The profile page now includes a thirty-day history of all potato given and received.
